name: reader_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
    
  animated_splash_screen: ^1.3.0
  # c
  cupertino_icons: ^1.0.2
  
  # f
  flutter_password_strength: ^0.1.6
  flutter_svg: ^1.1.6
  flextras: ^1.0.0


  # g
  get: ^4.6.5

  # i
  intl_phone_number_input: ^0.7.2

  #p
  pin_code_fields: ^7.4.0

  # r
  readmore: ^2.2.0
  
  # s
  stretchy_header: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: San Francisco
      fonts:
        - asset: assets/fonts/sanfrancisco.otf
        - asset: assets/fonts/sanfrancisco-ultralight.otf
          weight: 700
    - family: Proxi Nova
      fonts:
        - asset: assets/fonts/proxinova.otf
        - asset: assets/fonts/proxinova-light.otf
          weight: 700
