name: reader_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  
  # c
  cupertino_icons: ^1.0.2
  carousel_slider: ^4.2.1
  cached_network_image: ^3.2.3


  #d
  dropdown_button2: ^2.0.1
  dio: 

  # e
  expandable_text: ^2.3.0
  
  # f
  flutter_password_strength: ^0.1.6
  flutter_svg: ^2.0.7
  flextras: ^1.0.0
  flutter_custom_clippers: ^2.1.0
  flutter_staggered_animations: ^1.0.0
  flutter_rating_bar:
  fl_chart: ^0.63.0
  file_picker: ^5.3.2
  flutter_pdfview: ^1.3.1
  flutter_cache_manager: ^3.3.1


  # g
  get: ^4.6.5


  #h
  hive:
  hive_flutter:
 

  # i
  intl_phone_field: ^3.2.0
  intl: ^0.18.1

  #l
  liquid_pull_to_refresh: ^3.0.1

  #p
  pin_code_fields: ^8.0.1
  page_transition: "^2.0.9"
  phosphor_flutter: ^2.0.0
  percent_indicator:
  pull_to_refresh: ^2.0.0
  path:
  path_provider:
  

  # r
  readmore: ^2.2.0
  
  # s
  stretchy_header: ^2.0.0
  syncfusion_flutter_datepicker: ^22.1.38
  flutter_staggered_grid_view: 
  skeletonizer: ^0.7.0


  #u
  url_launcher: ^6.1.12

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  hive_generator:
  build_runner:







flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: San Francisco
      fonts:
        - asset: assets/fonts/sanfrancisco.otf
        - asset: assets/fonts/sanfrancisco-ultralight.otf
          weight: 700
    - family: Proxi Nova
      fonts:
        - asset: assets/fonts/proxinova.otf
        - asset: assets/fonts/proxinova-light.otf
          weight: 700
